name: plotter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - future==0.18.2
    - numpy==1.20.1
    - pyqtgraph==0.11.1
    - PyQt5==5.15.4
    - pyserial==3.5
    - qtwidgets==0.18
    - pyinstaller
